localStorage.setItem("products", JSON.stringify([
  {
    id: "byd-seal-u",
    name: "BYD Seal U DM-i",
    year: "2024",
    category: "Plug-in Hybrid SUV",
    price: "2,650,000 EGP",
    model: "models/2024_byd_seal_u_dm-i.glb",
    poster: "models/poster10-page2.png",
    numb1_sec2: "300+",
    para1_sec2: "This hybrid SUV delivers impressive horsepower, providing smooth, responsive, and highly efficient performance for both city and highway driving.",
    numb2_sec2: "70+",
    para2_sec2: "Provides an impressive number of kilometers of pure electric driving, making daily fuel-free commutes highly efficient and environmentally friendly.",
    numb3_sec2: "500+",
    para3_sec2: "Generates strong Newton-meters of torque, giving exceptionally responsive acceleration and powerful performance at any speed.",
    para_sec3: "The BYD Seal U DM-i is engineered to deliver a refined balance between performance, comfort, and advanced technology. Its intelligent plug-in hybrid system allows seamless switching between electric and hybrid driving modes, ensuring excellent fuel efficiency without sacrificing power. Inside, the SUV offers a premium cabin experience with modern design, smart connectivity, and advanced safety features. Designed for families and daily commuters, it provides a smooth, confident, and environmentally responsible driving experience in all conditions.",
    highlights_sec3: [
      "Efficient plug-in hybrid system",
      "Smooth and quiet electric driving",
      "Spacious and modern interior",
      "Advanced safety and driver assistance"
    ],
    poster2: "models/poster19.png",
  },

  {
    id: "byd-u9",
    name: "BYD Yangwang U9",
    year: "2024",
    category: "Electric Supercar",
    price: "4,504,000 EGP",
    model: "models/2024_byd_yangwang_u9.glb",
    poster: "models/poster11.png",
    display: { top: "2%", height: "107%" },
    numb1_sec2: "750+",
    para1_sec2: "This electric supercar offers extreme acceleration with precise handling, giving drivers an exhilarating experience.",
    numb2_sec2: "120+",
    para2_sec2: "Reaches top speeds with perfect control, delivering an exhilarating high-performance experience.",
    numb3_sec2: "900+",
    para3_sec2: "Delivers immense torque for ultra-responsive and thrilling acceleration.",
    para_sec3: "The Yangwang U9 represents the future of electric supercars by combining bold design with cutting-edge engineering. Built for performance enthusiasts, it delivers breathtaking acceleration, advanced aerodynamics, and a highly responsive electric drivetrain. Every detail is focused on speed, stability, and control, offering a driving experience that pushes the limits of modern electric performance while maintaining precision and confidence at extreme speeds.",
    highlights_sec3: [
      "Extreme electric acceleration",
      "Advanced aerodynamic design",
      "High-performance electric drivetrain",
      "Track-focused driving dynamics"
    ],
    poster2: "models/poster20.png",
  },

  {
    id: "byd-seal-u2",
    name: "BYD Seal",
    year: "2024",
    category: "Plug-in Hybrid SUV",
    price: "2,650,000 EGP",
    model: "models/2024_byd_seal.glb",
    poster: "models/poster12.png",
    display: { cameraOrbit: "35deg 70deg 0.15m", fieldOfView: "48deg", "camera-target": "0m 0.4m 0m", right: "-45%", top: "9%", height: "90%" },
    numb1_sec2: "350+",
    para1_sec2: "This hybrid SUV combines efficiency and comfort, delivering a smooth and practical driving experience.",
    numb2_sec2: "80+",
    para2_sec2: "Offers a strong electric driving range for fuel-free daily commuting.",
    numb3_sec2: "450+",
    para3_sec2: "Provides smooth torque delivery for confident acceleration.",
    para_sec3: "The BYD Seal is designed to meet the demands of modern drivers by blending sustainability with smart performance. Its refined interior, intelligent technology, and smooth hybrid powertrain ensure comfort during everyday driving. With a focus on efficiency, safety, and practicality, it offers a reliable and stylish solution for urban commuting and longer journeys alike.",
    highlights_sec3: [
      "Hybrid efficiency for daily driving",
      "Comfort-focused suspension setup",
      "Quiet electric operation",
      "Modern infotainment system"
    ],
    display2: { cameraOrbit: "90deg 90deg 0.1m", fieldOfView: "30deg", top: "-9%", right: "-47%" },
    poster2: "models/poster21.png",
  },

  {
    id: "audi-r8",
    name: "Audi R8 Coupe",
    year: "2019",
    category: "Sports Car",
    price: "3,200,000 EGP",
    model: "models/2019_audi_r8_coupe.glb",
    poster: "models/poster13.png",
    display: { fieldOfView: "20deg", top: "-10%", height: "123%" },
    numb1_sec2: "562",
    para1_sec2: "The iconic Audi R8 Coupe is powered by a naturally aspirated V10 engine.",
    numb2_sec2: "315",
    para2_sec2: "Achieves impressive top speeds with excellent stability.",
    numb3_sec2: "540+",
    para3_sec2: "Delivers powerful torque for thrilling acceleration.",
    para_sec3: "The Audi R8 Coupe blends motorsport heritage with everyday usability, creating a true supercar experience. Its naturally aspirated V10 engine delivers an unforgettable sound and instant response, while the precise handling and quattro all-wheel-drive system provide confidence at any speed. With its aggressive design and premium craftsmanship, the R8 stands as an icon of performance and engineering excellence.",
    highlights_sec3: [
      "Naturally aspirated V10 engine",
      "Quattro all-wheel drive",
      "Aggressive supercar design",
      "Premium interior craftsmanship"
    ]
    ,
    poster2: "models/poster22.png",
  },

  {
    id: "bmw-m850",
    name: "BMW M850i Gran Coupe",
    year: "2020",
    category: "Luxury Coupe",
    price: "3,800,000 EGP",
    model: "models/2020_bmw_m850i_gran_coupe.glb",
    poster: "models/poster14.png",
    display: { right: "-43%" },
    numb1_sec2: "523",
    para1_sec2: "A luxury performance coupe blending comfort and power.",
    numb2_sec2: "310",
    para2_sec2: "High top speed with smooth and refined driving.",
    numb3_sec2: "500+",
    para3_sec2: "Torque ensures effortless acceleration.",
    para_sec3: "The BMW M850i Gran Coupe is crafted for drivers who seek both luxury and performance. Its powerful engine, advanced driving technologies, and refined suspension deliver a smooth yet dynamic driving experience. Inside, premium materials, modern infotainment, and advanced safety systems create a sophisticated environment that makes every journey comfortable, confident, and engaging.",
    highlights_sec3: [
      "Twin-turbo V8 performance",
      "Luxury-focused interior design",
      "Advanced driving assistance",
      "Dynamic all-wheel drive"
    ]
        ,
    poster2: "models/poster23.png",
  },

  {
    id: "lotus-emira",
    name: "Lotus Emira V6",
    year: "2022",
    category: "Sports Car",
    price: "3,500,000 EGP",
    model: "models/2022_lotus_emira_v6.glb",
    poster: "models/poster15.png",
    display: { height: "112%", top: "-2%" },
    numb1_sec2: "400",
    para1_sec2: "A lightweight sports car built for driving purity.",
    numb2_sec2: "290",
    para2_sec2: "Strong top speed with excellent balance.",
    numb3_sec2: "420+",
    para3_sec2: "Instant torque for sharp acceleration.",
    para_sec3: "The Lotus Emira is designed with a pure focus on driving engagement and precision. Its lightweight chassis, finely tuned suspension, and responsive power delivery create an immersive driving experience. Built for enthusiasts, it delivers exceptional feedback, balance, and control, making every drive feel connected and rewarding on both road and track.",
    highlights_sec3: [
      "Lightweight chassis design",
      "Driver-focused cockpit",
      "Exceptional handling balance",
      "Engaging V6 performance"
    ]
       ,
    poster2: "models/poster24.png",
  },

  {
    id: "yangwang-u7",
    name: "BYD Yangwang U7",
    year: "2024",
    category: "Electric Luxury Sedan",
    price: "4,200,000 EGP",
    model: "models/2024_byd_yangwang_u7.glb",
    poster: "models/poster16.png",
    display: { fieldOfView: "20deg", right: "-42%" },
    numb1_sec2: "600+",
    para1_sec2: "A luxury electric sedan offering smooth and refined driving.",
    numb2_sec2: "150+",
    para2_sec2: "Long electric range for comfortable travel.",
    numb3_sec2: "700+",
    para3_sec2: "Effortless torque delivery for confident performance.",
    para_sec3: "The Yangwang U7 redefines electric luxury by combining elegant design with advanced electric technology. Its quiet performance, spacious interior, and intelligent systems create a refined driving experience. Designed for comfort and efficiency, it offers premium materials, smooth acceleration, and innovative features that elevate everyday driving into a truly luxurious experience.",
    highlights_sec3: [
      "Luxury electric drivetrain",
      "Silent and smooth ride quality",
      "High-end interior materials",
      "Advanced intelligent systems"
    ]
         ,
    poster2: "models/poster25.png",
  },

  {
    id: "mclaren-gt",
    name: "McLaren GT",
    year: "2020",
    category: "Luxury Sports Car",
    price: "5,100,000 EGP",
    model: "models/2020_mclaren_gt (1).glb",
    poster: "models/poster17.png",
    display: { right: "-42%" },
    numb1_sec2: "620",
    para1_sec2: "A grand tourer that balances speed and comfort.",
    numb2_sec2: "330",
    para2_sec2: "Impressive top speed with refined stability.",
    numb3_sec2: "680+",
    para3_sec2: "Strong torque for fast, smooth acceleration.",
    para_sec3: "The McLaren GT is designed for long-distance driving without sacrificing supercar performance. It combines powerful acceleration, refined handling, and a luxurious interior to deliver comfort on extended journeys. With its aerodynamic efficiency, advanced suspension, and elegant design, it offers a unique balance between everyday usability and thrilling performance.",
    highlights_sec3: [
      "Supercar-level performance",
      "Comfort-focused grand touring setup",
      "Elegant aerodynamic design",
      "Powerful twin-turbo engine"
    ]
             ,
    poster2: "models/poster26.png",
  },

  {
    id: "nissan-gtr",
    name: "Nissan GT-R",
    year: "2021",
    category: "Performance Sports Car",
    price: "3,900,000 EGP",
    model: "models/2017_nissan_gt-r_nismo.glb",
    poster: "models/poster18.png",
    display: { right: "-42%" },
    numb1_sec2: "565",
    para1_sec2: "Legendary performance with aggressive acceleration.",
    numb2_sec2: "315",
    para2_sec2: "High top speed with precise control.",
    numb3_sec2: "620+",
    para3_sec2: "Lightning-fast torque response.",
    para_sec3: "The Nissan GT-R is engineered for drivers who demand extreme performance and control. Its advanced all-wheel-drive system, precise handling, and powerful twin-turbo engine deliver relentless acceleration and confidence at high speeds. Combining track-inspired technology with everyday usability, the GT-R remains a benchmark in high-performance sports cars.",
    highlights_sec3: [
      "Advanced all-wheel-drive system",
      "Iconic aggressive styling",
      "Track-focused engineering",
      "High-performance twin-turbo V6"
    ]
       ,
    poster2: "models/poster27.png",
  }
]));
